### ISSUE TITLE
Working? :)

### ISSUE THREAD

**Issue by mario** [Monogramm/talk-signalmaster#1]
I was wondering if you ever got this actually working? :)

**Comment by madmath03** [comment]
Started but not had the time to finish it (yet). Even if Talk API is fully documented, it's a big challenge to implement all this so any help is appreciated 😉

**Comment by madmath03** [comment]
For info, NextCloud OpenSourced their high performance signaling server:
* https://nextcloud.com/blog/open-sourcing-talk-back-end-rc-of-talk-9-brings-lots-of-improvements/#hpb
* https://github.com/strukturag/nextcloud-spreed-signaling

This project is no longer necessary :wink:
